---

- name: Create PostgreSQL user
  become_user: postgres
  postgresql_user:
    name: "{{ postgres_user }}"
    

- name: Create PostgreSQL database
  become_user: postgres
  postgresql_db:
    name: "{{ postgres_db }}"
    owner: "{{ postgres_user }}"

- name: Grant read and write permissions to jumia on jumia_db
  become_user: postgres
  postgresql_privs:
    db: "{{ postgres_db }}"
    roles: "{{ postgres_user }}"
    objs: ALL_IN_SCHEMA
    privs: SELECT,INSERT,UPDATE,DELETE
