---

- name: Check if PostgreSQL user exists
  become_user: postgres
  shell: "psql -tAc \"SELECT 1 FROM pg_roles WHERE rolname='{{ postgres_user }}'\""
  register: user_exists

- name: Check if PostgreSQL database exists
  become_user: postgres
  shell: "psql -lqt | cut -d \\| -f 1 | grep -qw {{ postgres_db }}"
  register: db_exists
  ignore_errors: yes

- name: Create PostgreSQL user
  become_user: postgres
  command: "psql -c \"CREATE USER {{ postgres_user }} WITH PASSWORD '{{ postgres_password }}'\""
  when: not user_exists.stdout

- name: Create PostgreSQL database
  become_user: postgres
  command: "createdb {{ postgres_db }}"
  when: db_exists.rc != 0

- name: Grant privileges to user on database
  become_user: postgres
  command: "psql -d {{ postgres_db }} -c \"GRANT {{ postgres_privileges }} ON ALL TABLES IN SCHEMA public TO {{ postgres_user }};\""

- name: Copy sample.sql to remote host
  template:
    src: sample.sql
    dest: /tmp/sample.sql

- name: Create table in PostgreSQL database
  become_user: postgres
  command: "psql -d {{ postgres_db }} -f /tmp/sample.sql"
