---

- name: Create PostgreSQL user
  become_user: postgres
  command: "createuser {{ postgres_user }}"

- name: Create PostgreSQL database
  become_user: postgres
  command: "createdb {{ postgres_db }}"

- name: Grant privileges to user on database
  become_user: postgres
  command: "psql -c \"GRANT {{ postgres_privileges }} ON DATABASE {{ postgres_db }} TO {{ postgres_user }};\""
