- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Remove default Nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create Nginx load balancer configuration
  template:
    src: templates/load_balancer.conf.j2
    dest: /etc/nginx/conf.d/load_balancer.conf

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
