
- hosts: microservice
  become: yes
  roles:
    - role: docker-run
      vars:
        region: eu-west-1
        account_id: 992122884453
        repository_names:
          - validator-bkend
          - validator-ftend
        tag: ${{ github.sha }}

