- hosts: load_balancer
  become: yes
  roles:
    - ssh
    - role: networking
      vars:
        allowed_tcp_ports:
          - 80
          - 443
          - 1337
          - 8080
    - nginx-lb

- hosts: microservice
  become: yes
  roles:
    - ssh
    - role: networking
      vars:
        allowed_tcp_ports:
          - 80
          - 443
          - 8080
          - 1337
          - 5432
        
   
- hosts: database
  become: yes
  roles:
    - ssh
    - role: networking
      vars:
        allowed_tcp_ips: "{{ groups['backend'] }}"
        allowed_tcp_ports:
          - 80
          - 8080
          - 5432
    - role: networking   # allow ssh from all 
      vars:
        allowed_tcp_ports:
          - 1337
    - role: postgres
      vars:
        postgres_user: jumia
        postgres_db: jumia_phone_validator
        postgres_privileges: "ALL PRIVILEGES"
