- hosts: load_balancer
  become: yes
  roles:
    - ssh
    - role: networking
      vars:
        allowed_tcp_ports:
          - 80
          - 443
          - 1337
    - nginx-lb

- hosts: microservice
  become: yes
  roles:
    - ssh
    - role: networking
      vars:
        allowed_tcp_ports:
          - 80
          - 443
        
   
- hosts: database
  become: yes
  roles:
    - ssh
    - role: networking
      vars:
        allowed_tcp_ips:
          - "{{ hostvars['microservice'].ansible_host }}"
        allowed_tcp_ports:
          - 1337
    - role: postgres
      vars:
        postgres_user: jumia
        postgres_db: jumia_phone_validator
        postgres_privileges: "SELECT, INSERT, UPDATE, DELETE"
