- hosts: load_balancer
  become: yes
  roles:
    - ssh
    - role: networking
      vars:
        allowed_tcp_ports:
          - 80
          - 443
          - 1337

- hosts: microservice
  become: yes
  roles:
    - ssh
    - role: networking
      vars:
        allowed_tcp_ips:
          - "{{ hostvars['load_balancer'].ansible_host }}"
        allowed_tcp_ports:
          - 80
          - 443
          - 1337
