---
- name: Login to ECR
  command: aws ecr get-login-password --region {{ region }} | docker login --username AWS --password-stdin {{ account_id }}.dkr.ecr.{{ region }}.amazonaws.com

- name: Pull Docker image from ECR
  command: docker pull {{ account_id }}.dkr.ecr.{{ region }}.amazonaws.com/{{ repository_name }}:{{ tag }}

- name: Run Docker container
  command: docker run -d --name {{ container_name }} {{ account_id }}.dkr.ecr.{{ region }}.amazonaws.com/{{ repository_name }}:{{ tag }}


