---
- name: Ensure a user with root privileges exists
  user:
    name: jumia
    state: present
    group: root

- name: Allow the new user to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^jumia'
    line: 'jumia ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Update sshd_config file
  lineinfile:
     dest: /etc/ssh/sshd_config
     regexp: "{{ item.regexp }}"
     line: "{{ item.line }}"
  with_items:
    - { regexp: "^Port", line: "Port 1337" }
    - { regexp: "^PasswordAuthentication", line: "PasswordAuthentication no" }
    - { regexp: "^PermitRootLogin", line: "PermitRootLogin no" }
  notify:
    - restart ssh