---
- name: Allow incoming traffic on specified TCP ports
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
  with_items: "{{ allowed_tcp_ports }}"


- name: Allow incoming traffic from specified IP addresses
  iptables:
    chain: INPUT
    source: "{{ item }}"
    jump: ACCEPT
  with_items: "{{ allowed_tcp_ips }}"

- name: Allow outgoing traffic
  iptables:
    chain: INPUT
    match: conntrack
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Set default policy for INPUT chain to DROP
  iptables:
    chain: INPUT


